spring:
  mail:
    host: smtp.163.com # Sending mail server
    username: ENC(1Hka90x3Cb96gA+IkfpJ0AOWvfQjykbzt+AON79ERLbFR2RKvsx5Scajx6r9aRCbYWD5my0X9cu6dmw+dqvxcg==) # Email address for sending emails
    password: ENC(QIKAdUyVWdwRwQT5mjPevUDs1amJXp2C4RkX6KxHGx+hSM3ISjLiFIvuEe6HvzVVE+s6reD44S82GTt3eaB3qQ==) # Client authorization code
    properties.mail.smtp.port: 994 # 465 or 994
    from: ENC(gGCJwSbta1qflBB5QCnuTEOhVw7e+fRF5XIJGZpcfNL8FDtJMwKhrLFw7ProUvsF6pE9ESWDjEj/l892C2M9/A==) # The address from which the email is sent
    nickname: 花卷教育
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

sms:
  aliyun:
    accessKeyID: ENC(ydcPUJI25NlaMuSM8FBgvA1EmmQ4PNGFfkf45ZQUk53kupyYKqyZ41dF3+85MZo0adedE9s2gwr2c0tFcHZD3A==) # accessKeyID
    accessKeySecret: ENC(bD/ERE4bW+GGLD6A0JWaXioiEb91GDm2lbLICSq01GEk2j5aHivhvn68w8A0ZGOygqyu8aCwbS0dOIL/TbGnoQ==) # accessKeySecret
    domain: dysmsapi.aliyuncs.com
    regionId: cn-hangzhou
    templateCode: SMS_215344833 # your template code
    signName: 花卷买卖 # your signature