spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/breadroll-education?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: ENC(FIkYs+o3Yfyr2XUfs7uoouRhmrZhT7JakP9fLkMyE1dTvJGXaI4DadDC2luaxmAx)
    password: ENC(6yVq8H5ZljSHStQLw7vR0dyIkOJCMI4tbc8sUxCQHj3MvSCk7qq8UjhGQK2JQzGP)

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.qiudb.pojo
  configuration:
    mapUnderscoreToCamelCase: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    top:
      qiudb:
        mapper: debug