spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/breadroll-education?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: ENC(qHJh4UTPnlk6Vk9NnSRKjTPJZgDrOtYTtGwlUYhyVJRBmZNayKOcDJsRwZx/P+Rj)
    password: ENC(xjkNlTr31mXnEZo5W5A6HWoe/UQLRiQUZSavMjtuBTlpse0G1jGccoMSfp9BTtbk)

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.qiudb.pojo
  configuration:
    mapUnderscoreToCamelCase: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    top:
      qiudb:
        mapper: debug