spring:
  mail:
    host: smtp.163.com #发送邮件服务器
    username: 15233088662@163.com #发送邮件的邮箱地址
    password: PECCHGRXRGBJPLOY #客户端授权码，不是邮箱密码,网易的是自己设置的
    properties.mail.smtp.port: 994 #465或者994
    from: 15233088662@163.com # 发送邮件的地址，和上面username一致
    nickname: 花卷教育
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

sms:
  aliyun:
    accessKeyID: LTAI4GDr1DAsYncMPsk9Db59 # accessKeyID
    accessKeySecret: Qrxv4BgkI6sAYNpG7rX5IHWVc5mKoG # accessKeySecret
    domain: dysmsapi.aliyuncs.com # 固定不变
    regionId: cn-hangzhou # 固定不变
    templateCode: SMS_215344833 # 你的模板code
    signName: 花卷买卖 # 你的签名